## Overview

In this session, we will delve into using the NumPy library for financial data analysis. NumPy is a versatile Python library for numerical computations, and it plays a crucial role in performing various financial calculations and manipulations. We will use financial data examples to illustrate key concepts and operations.

## Table of Contents

1. **Introduction to NumPy for Finance**
   - What is NumPy?
   - Installation and Importing

2. **Array Creation and Attributes**
   - Creating NumPy Arrays
   - Array Attributes and Data Types

3. **Array Dimensions and Indexing**
   - Working with Different Dimensions
   - Array Indexing and Slicing

4. **Array Concatenation and Split**
   - Concatenating Arrays
   - Splitting Arrays

5. **Array Broadcasting and Mathematical Operations**
   - Understanding Array Broadcasting
   - Mathematical Operations on Arrays

6. **Iterating Arrays with nditer**
   - Using the nditer Function
   - Iterating Over Array Elements

7. **Manipulating Axes and Swapping Axes**
   - Rolling and Swapping Axes
   - Modifying Array Shape

8. **Copying and Views**
   - Copying vs. Views
   - Creating Views of Arrays

9. **Mathematical Functions and Operations**
   - Basic Mathematical Functions
   - Advanced Mathematical Operations

## Prerequisites

Before proceeding, you should have a basic understanding of Python programming. Ensure that you have Python installed on your system, along with the NumPy library.

## Section 1: Array Creation and Attributes

### 1.1 Problem Statement

As a financial analyst, you've been tasked with analyzing historical stock prices for a portfolio of companies. To perform these analyses, you need to create arrays to store the data and understand important array attributes and data types for further processing.

### 1.2 Creating NumPy Arrays

In financial data analysis, it's essential to efficiently store and manage numerical data. NumPy provides various methods for creating arrays. Let's explore how to create arrays for the historical stock prices of three companies: Company A, Company B, and Company C.

#### 1.2.1 Creating a Simple Array

In [1]:
import numpy as np

# Creating arrays for historical stock prices
company_a_prices = np.array([150, 155, 160, 158, 162])
company_b_prices = np.array([75.5, 77, 76, 78.5, 80])
company_c_prices = np.array([200, 198, 203, 197, 205])

# Display the arrays
print("Company A prices:", company_a_prices)
print("Company B prices:", company_b_prices)
print("Company C prices:", company_c_prices)

Company A prices: [150 155 160 158 162]
Company B prices: [75.5 77.  76.  78.5 80. ]
Company C prices: [200 198 203 197 205]


In [2]:
type(company_a_prices)

numpy.ndarray

#### 1.2.2 Creating a Range of Values

In [2]:
# Creating an array of days
days = np.arange(1, 6)

# Display the array
print("Days:", days)

Days: [1 2 3 4 5]


#### 1.2.3 Creating an Array of Zeros or Ones

In [3]:
# Creating an array of zeros for quantities
quantities = np.zeros(5)

# Creating an array of ones for weights
weights = np.ones(5)

# Display the arrays
print("Quantities:", quantities)
print("Weights:", weights)

Quantities: [0. 0. 0. 0. 0.]
Weights: [1. 1. 1. 1. 1.]


In [ ]:
np.linspace(start, stop, count)

### 1.3 Array Attributes and Data Types

When working with arrays, understanding their attributes and data types is crucial for effective analysis. Let's explore key attributes and data types.

#### 1.3.1 Shape of an Array

The shape of an array provides insights into its dimensions. Let's examine the shape of the arrays representing stock prices and quantities.


In [4]:
# Shape of company A prices array
print("Shape of Company A prices array:", company_a_prices.shape)

# Shape of quantities array
print("Shape of quantities array:", quantities.shape)

Shape of Company A prices array: (5,)
Shape of quantities array: (5,)


#### 1.3.2 Data Type of an Array

The data type of an array determines the type of elements it holds. Let's investigate the data types of the arrays representing stock prices and days.


In [5]:
# Data type of company B prices array
print("Data type of Company B prices array:", company_b_prices.dtype)

# Data type of days array
print("Data type of days array:", days.dtype)

Data type of Company B prices array: float64
Data type of days array: int64


### 1.4 Explanation of Concepts

- **Creating NumPy Arrays:** We used various methods to create arrays, such as `np.array()`, `np.arange()`, `np.zeros()`, and `np.ones()`. These methods help us efficiently organize and manage financial data.

- **Array Attributes and Data Types:** Understanding the `shape` of an array is crucial for determining its structure, and knowing the `data type` ensures accurate calculations and analyses.

## Section 2: Array Dimensions and Indexing

### 2.1 Problem Statement

As you continue your journey in financial analysis, you encounter larger datasets that require advanced techniques for handling multi-dimensional arrays and extracting specific information. In this section, we will explore these concepts using an extended dataset of historical stock prices for a portfolio of companies.

### 2.2 Working with Different Dimensions

Imagine you're analyzing a diverse portfolio of companies spanning various sectors. Let's create a 2D array representing historical stock prices for each company over multiple trading days.

#### 2.2.1 Creating an Extended 2D Array


In [3]:
import numpy as np

# Creating a larger 2D array for stock prices of six companies over ten days
stock_prices = np.array([[150, 155, 160, 158, 162, 159, 163, 162, 165, 168],
                         [75.5, 77, 76, 78.5, 80, 81, 82, 80, 79.5, 81],
                         [200, 198, 203, 197, 205, 210, 208, 215, 220, 218],
                         [40, 41, 42, 43, 44, 43.5, 45, 46, 47, 48],
                         [95, 94, 93, 92, 91, 90, 89, 88, 87, 86],
                         [120, 122, 125, 123, 128, 127, 126, 130, 135, 132]])

# Display the extended 2D array
print("Stock prices array:")
print(stock_prices)

Stock prices array:
[[150.  155.  160.  158.  162.  159.  163.  162.  165.  168. ]
 [ 75.5  77.   76.   78.5  80.   81.   82.   80.   79.5  81. ]
 [200.  198.  203.  197.  205.  210.  208.  215.  220.  218. ]
 [ 40.   41.   42.   43.   44.   43.5  45.   46.   47.   48. ]
 [ 95.   94.   93.   92.   91.   90.   89.   88.   87.   86. ]
 [120.  122.  125.  123.  128.  127.  126.  130.  135.  132. ]]


### 2.3 Array Indexing and Slicing

Let's dive into indexing and slicing this larger array to extract valuable insights about the stock prices.

#### 2.3.1 Indexing for Specific Companies and Days

In [6]:
stock_prices[3, 4]

44.0

In [7]:
# Accessing the stock price of Company D on Day 5
price_company_d_day_5 = stock_prices[3, 4]
print("Stock price of Company D on Day 5:", price_company_d_day_5)

Stock price of Company D on Day 5: 44.0


#### 2.3.2 Slicing for Analysis

In [7]:
stock_prices[3,0:5]

array([40., 41., 42., 43., 44.])

In [9]:
# Slicing the stock prices for the first five days of all companies
first_five_days_prices = stock_prices[:, :5]
print("Stock prices for the first five days:")
print(first_five_days_prices)

# Slicing the stock prices for the last three days of Company F
last_three_days_company_f = stock_prices[5, -3:]
print("Stock prices for the last three days of Company F:")
print(last_three_days_company_f)

Stock prices for the first five days:
[[150.  155.  160.  158.  162. ]
 [ 75.5  77.   76.   78.5  80. ]
 [200.  198.  203.  197.  205. ]
 [ 40.   41.   42.   43.   44. ]
 [ 95.   94.   93.   92.   91. ]
 [120.  122.  125.  123.  128. ]]
Stock prices for the last three days of Company F:
[130. 135. 132.]


In [8]:
stock_prices[:,::2]

array([[150. , 160. , 162. , 163. , 165. ],
       [ 75.5,  76. ,  80. ,  82. ,  79.5],
       [200. , 203. , 205. , 208. , 220. ],
       [ 40. ,  42. ,  44. ,  45. ,  47. ],
       [ 95. ,  93. ,  91. ,  89. ,  87. ],
       [120. , 125. , 128. , 126. , 135. ]])

In [16]:
stock_prices[0,0:9:2]

array([150., 160., 162., 163., 165.])

In [18]:
stock_prices[:,-1] = 0

In [20]:
print(stock_prices)

[[150.  155.  160.  158.  162.  159.  163.  162.  165.    0. ]
 [ 75.5  77.   76.   78.5  80.   81.   82.   80.   79.5   0. ]
 [200.  198.  203.  197.  205.  210.  208.  215.  220.    0. ]
 [ 40.   41.   42.   43.   44.   43.5  45.   46.   47.    0. ]
 [ 95.   94.   93.   92.   91.   90.   89.   88.   87.    0. ]
 [120.  122.  125.  123.  128.  127.  126.  130.  135.    0. ]]


In [24]:
stock_prices[stock_prices > 100]

array([150., 155., 160., 158., 162., 159., 163., 162., 165., 200., 198.,
       203., 197., 205., 210., 208., 215., 220., 120., 122., 125., 123.,
       128., 127., 126., 130., 135.])

In [25]:
ar = np.zeros((8,8), dtype=int)

In [26]:
ar[::2, ::2] = 1

In [28]:
ar[1::2, 1::2] = 1

In [30]:
ar

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [41]:
check = np.arange(0,64).reshape(8,8)

In [42]:
check

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [43]:
check[check%2==0] = 0

In [46]:
check[check != 0] = 1

In [47]:
check

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 2.4 Explanation of Concepts

- **Working with Different Dimensions:** In a realistic financial analysis scenario, multi-dimensional arrays efficiently accommodate diverse datasets, enhancing data organization and analysis.

- **Array Indexing and Slicing:** Indexing and slicing help extract targeted information from arrays, enabling focused analysis on specific companies or time periods.


## Section 3: Array Concatenation and Split

### 3.1 Problem Statement

As a financial analyst specializing in investment portfolios, your ability to analyze and extract insights from diverse financial data is crucial. Efficiently combining and splitting arrays is essential for comprehensive analysis. In this section, we will delve into the strategic applications of array concatenation and splitting using a comprehensive dataset of historical stock prices.

### 3.2 Array Concatenation and Stacking for Portfolio Insight

Imagine you're analyzing the quarterly stock prices of two companies, Company P and Company Q, over four consecutive quarters: Q1, Q2, Q3, and Q4. Your goal is to create a consolidated dataset that enables a comparative analysis of quarterly performance.

#### 3.2.1 Concatenating Along Axis=0 and Axis=1

In [48]:
import numpy as np

# Historical stock prices for Company P in Q1, Q2, Q3, and Q4
stock_prices_p = np.array([[150, 155, 160, 158, 162],
                           [165, 168, 170, 172, 175],
                           [180, 182, 185, 188, 190],
                           [195, 198, 200, 202, 205]])

# Historical stock prices for Company Q in Q1, Q2, Q3, and Q4
stock_prices_q = np.array([[75.5, 77, 76, 78.5, 80],
                           [82, 81, 83, 84, 85],
                           [87, 89, 88, 90, 91],
                           [92, 94, 95, 96, 98]])

# Concatenating the arrays along axis=0 for comprehensive analysis
consolidated_stock_prices = np.concatenate((stock_prices_p, stock_prices_q), axis=0)

# Display the consolidated array for Company P and Company Q
print("Consolidated stock prices for Companies P and Q (axis=0):")
print(consolidated_stock_prices)

# Concatenating the arrays along axis=1 for quarter-wise comparison
quarterly_comparison_stock_prices = np.concatenate((stock_prices_p, stock_prices_q), axis=1)

# Display the consolidated array for Company P and Company Q (axis=1)
print("\nQuarterly comparison stock prices for Companies P and Q (axis=1):")
print(quarterly_comparison_stock_prices)

Consolidated stock prices for Companies P and Q (axis=0):
[[150.  155.  160.  158.  162. ]
 [165.  168.  170.  172.  175. ]
 [180.  182.  185.  188.  190. ]
 [195.  198.  200.  202.  205. ]
 [ 75.5  77.   76.   78.5  80. ]
 [ 82.   81.   83.   84.   85. ]
 [ 87.   89.   88.   90.   91. ]
 [ 92.   94.   95.   96.   98. ]]

Quarterly comparison stock prices for Companies P and Q (axis=1):
[[150.  155.  160.  158.  162.   75.5  77.   76.   78.5  80. ]
 [165.  168.  170.  172.  175.   82.   81.   83.   84.   85. ]
 [180.  182.  185.  188.  190.   87.   89.   88.   90.   91. ]
 [195.  198.  200.  202.  205.   92.   94.   95.   96.   98. ]]


### 3.3 Array Splitting for In-Depth Analysis

To conduct more detailed assessments, you'll focus on the quarterly performance of Company P and Company Q. By splitting arrays, you can extract specific quarters for targeted analysis.

#### 3.3.1 Splitting for Company-Specific Analysis

In [51]:
# Splitting the consolidated array for Company P and Company Q along axis=0
print(consolidated_stock_prices)
split_stock_prices_P, split_stock_prices_Q = np.split(consolidated_stock_prices, 2, axis=0)
# Display the split arrays for Company P and Company Q
print("Split stock prices arrays for Companies P and Q:")
print("Company P:")
print(split_stock_prices_P)
print("\nCompany Q:")
print(split_stock_prices_Q)

[[150.  155.  160.  158.  162. ]
 [165.  168.  170.  172.  175. ]
 [180.  182.  185.  188.  190. ]
 [195.  198.  200.  202.  205. ]
 [ 75.5  77.   76.   78.5  80. ]
 [ 82.   81.   83.   84.   85. ]
 [ 87.   89.   88.   90.   91. ]
 [ 92.   94.   95.   96.   98. ]]
Split stock prices arrays for Companies P and Q:
Company P:
[[150. 155. 160. 158. 162.]
 [165. 168. 170. 172. 175.]
 [180. 182. 185. 188. 190.]
 [195. 198. 200. 202. 205.]]

Company Q:
[[75.5 77.  76.  78.5 80. ]
 [82.  81.  83.  84.  85. ]
 [87.  89.  88.  90.  91. ]
 [92.  94.  95.  96.  98. ]]


### 3.4 Explanation of Concepts

- **Array Concatenation for Comprehensive Insights:** Concatenating arrays along axis=0 is ideal when combining data from multiple quarters for the same company. Concatenating along axis=1 is useful for quarter-wise comparison across different companies.

- **Array Splitting for Focused Analysis:** Splitting arrays helps you isolate specific data segments for targeted assessments, facilitating in-depth evaluations of individual companies or quarters.

## Section 4: Array Broadcasting

### 4.1 Problem Statement

As a financial analyst, you often encounter scenarios where you need to perform element-wise operations on arrays of different shapes. Array broadcasting is a powerful tool that allows you to efficiently apply operations to arrays with varying dimensions. In this section, we will dive deep into the concept of array broadcasting using financial data to illustrate its practical applications.

### 4.2 Understanding Array Broadcasting

Imagine you're analyzing the quarterly revenue growth of two companies, Company X and Company Y. You have their revenue data as well as a global market factor that affects each quarter's revenue. The challenge is that the market factor is a scalar value, whereas the revenue data is an array. Array broadcasting enables you to perform element-wise multiplication effectively.

#### 4.2.1 Broadcasting for Revenue Growth Analysis

In [62]:
arr_1 = np.random.randint(10,99, 5)
arr_2 = np.random.randint(10,99,20).reshape(4,5)

In [63]:
print('arr_1 :\n{} \n arr_2:\n{}'.format(arr_1, arr_2))
print('arr_1 + arr_2: \n{}'.format(arr_1+arr_2))

arr_1 :
[83 19 18 67 44] 
 arr_2:
[[13 78 65 50 65]
 [52 61 61 92 75]
 [17 59 79 94 70]
 [62 72 57 50 86]]
arr_1 + arr_2: 
[[ 96  97  83 117 109]
 [135  80  79 159 119]
 [100  78  97 161 114]
 [145  91  75 117 130]]


In [66]:
np.concatenate((arr_1.reshape(1,5), arr_2), axis=0)

array([[83, 19, 18, 67, 44],
       [13, 78, 65, 50, 65],
       [52, 61, 61, 92, 75],
       [17, 59, 79, 94, 70],
       [62, 72, 57, 50, 86]])

In [57]:
arr_1.reshape(1,5)

array([[44, 52, 54, 39, 98]])

In [56]:
np.broadcast_to(arr_1, (4,5))

array([[44, 52, 54, 39, 98],
       [44, 52, 54, 39, 98],
       [44, 52, 54, 39, 98],
       [44, 52, 54, 39, 98]])

In [58]:
arr_1 = np.random.randint(10,99, 4).reshape(4,1)
arr_2 = np.random.randint(10,99,20).reshape(4,5)

In [61]:
print('arr_1 :\n{} \n arr_2:\n{}'.format(arr_1, arr_2))
print('arr_1 + arr_2: \n{}'.format(arr_1+arr_2))

arr_1 :
[[32]
 [72]
 [58]
 [28]] 
 arr_2:
[[96 24 36 81 82]
 [96 97 15 86 74]
 [73 27 81 52 33]
 [87 10 45 48 44]]
arr_1 + arr_2: 
[[128  56  68 113 114]
 [168 169  87 158 146]
 [131  85 139 110  91]
 [115  38  73  76  72]]


In [68]:
arr_2 + 5

array([[18, 83, 70, 55, 70],
       [57, 66, 66, 97, 80],
       [22, 64, 84, 99, 75],
       [67, 77, 62, 55, 91]])

In [69]:
np.broadcast_to(5, (4,5))

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [15]:
import numpy as np

# Quarterly revenue data for Company X and Company Y
revenue_x = np.array([[100, 110, 115, 120],
                      [130, 125, 135, 140],
                      [145, 150, 155, 160]])

revenue_y = np.array([[80, 85, 90, 95],
                      [105, 100, 110, 115],
                      [120, 125, 130, 135]])

# Global market factor affecting revenue growth
market_factor = 1.05 
# Suppose the market factor for Y1 = 1.05, Y2 = 1.11, Y3=1.14
# Calculate adjusted revenew for the 2 companies

# Applying array broadcasting to perform element-wise multiplication
adjusted_revenue_x = revenue_x * market_factor
adjusted_revenue_y = revenue_y * market_factor

# Display the adjusted revenue arrays for Company X and Company Y
print("Adjusted revenue for Company X:")
print(adjusted_revenue_x)

print("\nAdjusted revenue for Company Y:")
print(adjusted_revenue_y)

Adjusted revenue for Company X:
[[105.   115.5  120.75 126.  ]
 [136.5  131.25 141.75 147.  ]
 [152.25 157.5  162.75 168.  ]]

Adjusted revenue for Company Y:
[[ 84.    89.25  94.5   99.75]
 [110.25 105.   115.5  120.75]
 [126.   131.25 136.5  141.75]]


In [74]:
import numpy as np

# Quarterly revenue data for Company X and Company Y
revenue_x = np.array([[100, 110, 115, 120],
                      [130, 125, 135, 140],
                      [145, 150, 155, 160]])

revenue_y = np.array([[80, 85, 90, 95],
                      [105, 100, 110, 115],
                      [120, 125, 130, 135]])

# Global market factor affecting revenue growth
# Suppose the market factor Q1, Q2, Q3, Q4 = 1.15, 1.13, 1.08, 1.16
# It is increased by 5% every year for all Quarters
# Calculate the adjusted revenue for the companies for next 3 years


# Create market factor array of shape(3,4) for all 3 years using concat (2 step)
# [market_factor,
#  market_factor*1.05,
# (market_factor*1.05)*1.05]


market_factor = np.array([1.15, 1.13, 1.08, 1.16], ndmin=2)
market_factor

array([[1.15, 1.13, 1.08, 1.16]])

### 4.3 Broadcasting with Arrays of Different Dimensions

In financial analysis, you often encounter scenarios where you need to combine data from multiple sources for comparison. Broadcasting allows you to perform operations even when the arrays have different dimensions.

#### 4.3.1 Broadcasting for Cross-Company Comparison


In [16]:
# Quarterly expenses data for Company X and Company Y
expenses_x = np.array([60, 65, 70, 75])
expenses_y = np.array([45, 50, 55, 60])

# Applying array broadcasting for cross-company comparison
expense_ratio_x = revenue_x / expenses_x
expense_ratio_y = revenue_y / expenses_y

# Display the expense ratios for Company X and Company Y
print("Expense ratios for Company X:")
print(expense_ratio_x)

print("\nExpense ratios for Company Y:")
print(expense_ratio_y)

Expense ratios for Company X:
[[1.66666667 1.69230769 1.64285714 1.6       ]
 [2.16666667 1.92307692 1.92857143 1.86666667]
 [2.41666667 2.30769231 2.21428571 2.13333333]]

Expense ratios for Company Y:
[[1.77777778 1.7        1.63636364 1.58333333]
 [2.33333333 2.         2.         1.91666667]
 [2.66666667 2.5        2.36363636 2.25      ]]


### 4.4 Broadcasting Rules and Implications

Understanding the broadcasting rules is crucial to ensure accurate and meaningful calculations. NumPy follows specific rules to determine how arrays of different shapes are broadcasted.

#### 4.4.1 Broadcasting Rules and Examples

In [17]:
# Quarterly profit data for Company X and Company Y
profit_x = np.array([[40, 45, 50, 55],
                     [60, 55, 65, 70],
                     [75, 80, 85, 90]])

profit_y = np.array([[30, 35, 40, 45],
                     [50, 45, 55, 60]])

# Broadcasting with arrays of different dimensions
if profit_x.shape != profit_y.shape:
    # Reshaping profit_y to match the shape of profit_x
    profit_y_reshaped = profit_y.reshape(2, 4)
    combined_profit = profit_x + profit_y_reshaped
else:
    combined_profit = profit_x + profit_y

# Display the combined profit array for Company X and Company Y
print("Combined profit for Company X and Company Y:")
print(combined_profit)

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

## Section 5: Array Iteration and Manipulation

### 5.1 Problem Statement

As a financial analyst, efficiently iterating through arrays and performing manipulations is essential for extracting insights from complex financial data. In this section, we will explore array iteration using `nditer` and manipulation techniques that include reshaping, rolling, and swapping axes, using 3D arrays to showcase their practical applications.

### 5.2 Array Iteration with nditer

Imagine you're analyzing quarterly sales data for two products, Product X and Product Y, across different regions. You want to calculate the total sales for each product in each region and then determine the overall average sales.

#### 5.2.1 Iterating Through Sales Data

In [80]:
sales_x = np.array([[[120, 130], [140, 150]],
                    [[160, 170], [180, 190]],
                    [[200, 210], [220, 230]]])


In [81]:
for i in sales_x:
    for j in i:
        for k in j:
            print(k, end=', ')

120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 

In [78]:
for i in np.nditer(sales_x):
    print(i, end=', ')

120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 

In [85]:
sales_x

array([[[120, 130],
        [140, 150]],

       [[160, 170],
        [180, 190]],

       [[200, 210],
        [220, 230]]])

In [19]:
import numpy as np

# Quarterly sales data for Product X and Product Y across regions
sales_x = np.array([[[120, 130], [140, 150]],
                    [[160, 170], [180, 190]],
                    [[200, 210], [220, 230]]])

sales_y = np.array([[[80, 90], [100, 110]],
                    [[120, 130], [140, 150]],
                    [[160, 170], [180, 190]]])

# Using nditer to iterate through 3D sales arrays
total_sales = 0
num_entries = 0

with np.nditer([sales_x, sales_y]) as it:
    for x, y in it:
        total_sales += x + y
        num_entries += 1

average_sales = total_sales / num_entries

# Display total and average sales
print("Total sales:", total_sales)
print("Average sales:", average_sales)

Total sales: 3720
Average sales: 310.0


In this example, the `sales_x` and `sales_y` arrays represent the quarterly sales data for Product X and Product Y across different regions. The first axis represents the quarters, the second axis represents the regions, and the third axis represents the actual sales data.

### 5.3 Array Manipulation: Reshaping, Rolling, and Swapping Axes

#### 5.3.1 Reshaping 3D Data for Analysis

In [87]:
# Quarterly profit data for Product X
profit_x = np.array([[[40, 50], [60, 70]],
                     [[80, 90], [100, 110]],
                     [[120, 130], [140, 150]]])

In [93]:
profit_x.shape

(3, 2, 2)

In [95]:
profit_x
# Axis=0 P
# Axis=1 Y
# Axis=2  Q

# Desired - Axis0: Y, Axis1: Prod, Axis2: Q

np.swapaxes(profit_x, 0, 1).shape

(2, 3, 2)

In [96]:
np.swapaxes(profit_x, 0, 1)

array([[[ 40,  50],
        [ 80,  90],
        [120, 130]],

       [[ 60,  70],
        [100, 110],
        [140, 150]]])

In [101]:
profit = np.random.randint(10,99, 24).reshape(3,2,4)
# Profits fpr 3 products, 2 years and 4 Quarters
profit.shape

(3, 2, 4)

In [103]:
# Product-vise comparison for 2 years and their quarters
profit

array([[[94, 75, 81, 25],
        [55, 32, 58, 87]],

       [[43, 41, 93, 26],
        [91, 65, 68, 88]],

       [[22, 70, 37, 32],
        [21, 69, 74, 29]]])

In [106]:
# Present Quarter vise comparison for both years for all products.
print(np.swapaxes(profit,0,2))
# present how Q1 performed for Y1 and Y2 for all three products
print(np.swapaxes(profit,0,2)[0])

[[[94 43 22]
  [55 91 21]]

 [[75 41 70]
  [32 65 69]]

 [[81 93 37]
  [58 68 74]]

 [[25 26 32]
  [87 88 29]]]
[[94 43 22]
 [55 91 21]]


In [20]:
# Quarterly profit data for Product X
profit_x = np.array([[[40, 50], [60, 70]],
                     [[80, 90], [100, 110]],
                     [[120, 130], [140, 150]]])

# Reshaping the profit data for analysis
reshaped_profit_x = profit_x.reshape(2, 3, 2)

# Display the reshaped profit array for Product X
print("Reshaped profit array for Product X:")
print(reshaped_profit_x)

Reshaped profit array for Product X:
[[[ 40  50]
  [ 60  70]
  [ 80  90]]

 [[100 110]
  [120 130]
  [140 150]]]


In this example, the `profit_x` array represents quarterly profit data for Product X. The reshaped array `reshaped_profit_x` has dimensions (2, 3, 2), where the first axis represents a different perspective of the data.

#### 5.3.2 Rolling and Swapping Axes in 3D

In [21]:
# Quarterly expense data for Product Y
expenses_y = np.array([[[20, 25], [30, 35]],
                       [[40, 45], [50, 55]],
                       [[60, 65], [70, 75]]])

# Rolling the expense data to shift columns in each region
rolled_expenses_y = np.roll(expenses_y, shift=1, axis=2)

# Display the rolled expense array for Product Y
print("Rolled expense array for Product Y:")
print(rolled_expenses_y)

# Swapping axes for profit data of Product X
swapped_axes_profit_x = np.swapaxes(reshaped_profit_x, axis1=0, axis2=2)

# Display the profit array with swapped axes for Product X
print("Profit array with swapped axes for Product X:")
print(swapped_axes_profit_x)

Rolled expense array for Product Y:
[[[25 20]
  [35 30]]

 [[45 40]
  [55 50]]

 [[65 60]
  [75 70]]]
Profit array with swapped axes for Product X:
[[[ 40 100]
  [ 60 120]
  [ 80 140]]

 [[ 50 110]
  [ 70 130]
  [ 90 150]]]


In this example, the `expenses_y` array represents quarterly expense data for Product Y. The rolling and swapping operations involve manipulating axes to gain different insights from the data.

## Section 6: Array Copy and Views

### 6.1 Problem Statement

As a financial analyst, you frequently work with large datasets and need to manage data efficiently. In this section, we will delve into the concepts of array copying and creating views, essential for data management, analysis, and making informed financial decisions.

### 6.2 Array Copying

Consider a scenario where you have quarterly revenue data for two companies, Company P and Company Q, and you want to create a copy of the data for further analysis. It's crucial to understand the distinction between a shallow copy and a deep copy.

#### 6.2.1 Creating Shallow and Deep Copies


In [108]:
revenue_p_b = revenue_p

In [109]:
revenue_p

array([250, 210, 220, 230])

In [111]:
revenue_p_b[-1] = 0

In [112]:
revenue_p

array([250, 210, 220,   0])

In [119]:
import numpy as np

# Quarterly revenue data for Company P and Company Q
revenue_p = np.array([200, 210, 220, 230])
revenue_q = np.array([180, 190, 200, 210])
# Creating a shallow copy
shallow_copy_p = revenue_p.view()
# Creating a deep copy
deep_copy_q = revenue_q.copy()
# Modifying the shallow copy and deep copy
shallow_copy_p[3] = 250
shallow_copy_p.shape = [2,2]
deep_copy_q[0] = 160
deep_copy_q.shape = [2,2]

# Display the original, shallow copy, and deep copy arrays
print("Original revenue data for Company P:")
print(revenue_p)
print("\nShallow copy of revenue data for Company P:")
print(shallow_copy_p)
print("\nDeep copy of revenue data for Company Q:")
print(revenue_q)
print("\nDeep copy of revenue data for Company Q:")
print(deep_copy_q)

Original revenue data for Company P:
[200 210 220 250]

Shallow copy of revenue data for Company P:
[[200 210]
 [220 250]]

Deep copy of revenue data for Company Q:
[180 190 200 210]

Deep copy of revenue data for Company Q:
[[160 190]
 [200 210]]


### 6.3 Creating Views

Suppose you're analyzing quarterly expenses data for Company R and you want to create a view that shows expenses above a certain threshold. Views provide a memory-efficient way to manipulate and analyze data without creating a separate copy.

#### 6.3.1 Creating Views for Selective Analysis

In [24]:
# Quarterly expenses data for Company R
expenses_r = np.array([70, 80, 90, 100])

# Creating a view for expenses above a threshold
threshold = 85
above_threshold_view = expenses_r[expenses_r > threshold]

# Modifying the view
above_threshold_view[0] = 110

# Display the original expenses array and the view
print("Original expenses data for Company R:")
print(expenses_r)

print("\nView of expenses above threshold for Company R:")
print(above_threshold_view)

Original expenses data for Company R:
[ 70  80  90 100]

View of expenses above threshold for Company R:
[110 100]


## Section 7: Mathematical Functions and Operations

### 7.1 Problem Statement

As a financial analyst, performing mathematical calculations on financial data is a fundamental aspect of your role. In this section, we will delve into a wide range of mathematical functions and operations provided by NumPy, tailored to the specific needs of financial data analysis.

### 7.2 Basic Mathematical Functions

Let's consider a scenario where you're analyzing investment growth for a portfolio over several years. You need to calculate the compound annual growth rate (CAGR) to evaluate the overall performance.

#### 7.2.1 Calculating Compound Annual Growth Rate (CAGR)


In [25]:
import numpy as np

# Investment value over 5 years
investment_value = np.array([1000, 1200, 1500, 1800, 2000])

# Calculate the CAGR
years = len(investment_value)
initial_value = investment_value[0]
final_value = investment_value[-1]
cagr = ((final_value / initial_value) ** (1 / years)) - 1

# Display the CAGR as a percentage
print("Compound Annual Growth Rate (CAGR): {:.2%}".format(cagr))

Compound Annual Growth Rate (CAGR): 14.87%


### 7.3 Element-wise Operations

Suppose you're analyzing stock prices for two companies, Company X and Company Y, over a specific period. You want to calculate the daily percentage change in stock prices and assess their correlation.

#### 7.3.1 Calculating Percentage Change and Correlation

In [120]:
# Stock prices for Company X and Company Y over 5 days
prices_x = np.array([50, 52, 55, 53, 51])
prices_y = np.array([70, 72, 75, 76, 78])

# Calculate the daily percentage change in stock prices
percentage_change_x = np.diff(prices_x) / prices_x[:-1]
percentage_change_y = np.diff(prices_y) / prices_y[:-1]


In [122]:
np.diff(prices_x)

array([ 2,  3, -2, -2])

In [121]:
prices_x[:-1]

array([50, 52, 55, 53])

In [123]:
np.corrcoef(percentage_change_x, percentage_change_y)

array([[1.        , 0.81428963],
       [0.81428963, 1.        ]])

In [26]:
# Stock prices for Company X and Company Y over 5 days
prices_x = np.array([50, 52, 55, 53, 51])
prices_y = np.array([70, 72, 75, 76, 78])

# Calculate the daily percentage change in stock prices
percentage_change_x = np.diff(prices_x) / prices_x[:-1]
percentage_change_y = np.diff(prices_y) / prices_y[:-1]

# Calculate the correlation coefficient between the two stocks
correlation_coefficient = np.corrcoef(percentage_change_x, percentage_change_y)[0, 1]

# Display the daily percentage change and correlation
print("Daily Percentage Change for Company X:", percentage_change_x)
print("Daily Percentage Change for Company Y:", percentage_change_y)
print("Correlation Coefficient:", correlation_coefficient)

Daily Percentage Change for Company X: [ 0.04        0.05769231 -0.03636364 -0.03773585]
Daily Percentage Change for Company Y: [0.02857143 0.04166667 0.01333333 0.02631579]
Correlation Coefficient: 0.8142896256383058


### 7.4 Aggregation and Summary Statistics

Imagine you're analyzing the annual sales data for a company, and you want to determine the average, minimum, and maximum sales.

#### 7.4.1 Calculating Aggregation and Summary Statistics

In [124]:
# Annual sales data for a company over 5 years (in thousands)
annual_sales = np.array([2500, 2800, 3200, 3000, 3500])

# Calculate the average, minimum, and maximum sales
average_sales = np.mean(annual_sales)
min_sales = np.min(annual_sales)
max_sales = np.max(annual_sales)

# Display the aggregation and summary statistics
print("Average Annual Sales:", average_sales)
print("Minimum Annual Sales:", min_sales)
print("Maximum Annual Sales:", max_sales)

Average Annual Sales: 3000.0
Minimum Annual Sales: 2500
Maximum Annual Sales: 3500


In [125]:
np.var(annual_sales)

116000.0

In [126]:
np.std(annual_sales)

340.58772731852804

In [127]:
annual_sales = np.random.randint(2000,3000,50).reshape(10,5)

In [128]:
annual_sales

array([[2139, 2924, 2470, 2496, 2404],
       [2904, 2901, 2222, 2290, 2145],
       [2817, 2394, 2409, 2634, 2102],
       [2814, 2913, 2076, 2156, 2503],
       [2740, 2775, 2579, 2474, 2546],
       [2309, 2402, 2824, 2366, 2422],
       [2638, 2652, 2398, 2704, 2549],
       [2886, 2439, 2296, 2221, 2132],
       [2480, 2109, 2222, 2337, 2137],
       [2292, 2689, 2245, 2266, 2235]])

In [129]:
np.mean(annual_sales)

2461.54

In [130]:
np.mean(annual_sales, axis=0)

array([2601.9, 2619.8, 2374.1, 2394.4, 2317.5])

In [131]:
np.mean(annual_sales, axis=1)

array([2486.6, 2492.4, 2471.2, 2492.4, 2622.8, 2464.6, 2588.2, 2394.8,
       2257. , 2345.4])

In [132]:
X = np.random.randint(10,99,40).reshape(10,4)
y = np.random.randint(10,99,10).reshape(-1,1)

In [133]:
X

array([[86, 35, 53, 69],
       [53, 60, 85, 73],
       [32, 41, 81, 95],
       [91, 56, 58, 70],
       [22, 67, 69, 18],
       [50, 67, 20, 33],
       [88, 98, 54, 56],
       [71, 27, 82, 52],
       [75, 87, 92, 71],
       [30, 44, 59, 97]])

In [134]:
y

array([[26],
       [18],
       [85],
       [14],
       [36],
       [90],
       [32],
       [26],
       [81],
       [23]])

In [135]:
coeff, intercept = np.random.randint(1,9,4), np.random.randint(10,19,1)
coeff, intercept

(array([8, 4, 5, 3]), array([15]))